[package]
name = "kawari"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kawari-frontier"

[[bin]]
name = "kawari-admin"

[[bin]]
name = "kawari-login"

[[bin]]
name = "kawari-patch"

[profile.release]
lto = true
strip = true
opt-level = "z"
codegen-units = 1
panic = "abort"

[dependencies]
axum = { version = "0.6.20", features = ["json", "tokio", "http1", "form", "query", "headers"], default-features = false }
serde_json = { version = "1.0.91", default-features = false }
tokio = { version = "1.32.0", features = ["macros", "rt", "rt-multi-thread"], default-features = false }
tracing = { version = "0.1.37", default-features = false }
serde = { version = "1.0.188", features = ["derive"], default-features = false }
tracing-subscriber = { version = "0.3.17", features = ["fmt"], default-features = false }